### ISSUE TITLE
Deleted items csv

### ISSUE THREAD

**Issue by ruetz007** [BTAA-Geospatial-Data-Project/dcat-metadata#10]
Change deleted items to only gather ids

JsonComparison.py

**Comment by karenmajewicz** [comment]
also add column for code/portalName

**Comment by ruetz007** [comment]
Is there a set of inputs I could use for testing this? @karenmajewicz @smit1975 @mkernik

**Comment by karenmajewicz** [comment]
A JSON from 2017 for anything starting with 06a should produce several deleted items (https://github.com/BTAA-Geospatial-Data-Project/dcat-metadata/tree/working/jsons)

**Comment by ruetz007** [comment]
Resolved. JsonComparison.py in the workingEVR branch has these changes.
