### ISSUE TITLE
Fix Baltimore County link (04b-24005)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/dcat-metadata#28]
new portal link is: https://bcstat-bc-gis.hub.arcgis.com/pages/gisopen-data

**Comment by Ziiiiing** [comment]
Baltimore County link (04b-24005):
- old JSON-formatted metadata link: `https://bcstat-bc-gis.hub.arcgis.com/data.json`
- new JSON-formatted metadata link: `https://bcstat-bc-gis.hub.arcgis.com/pages/gisopen-data/data.json`

**Comment by karenmajewicz** [comment]
no change needed
