### ISSUE TITLE
10b-55059 Add Kenosha County WI to arcportals

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/dcat-metadata#42]
Code: 10b-55059
New ArcGIS Hub API here: https://dataportal.kenoshacounty.org/data.json

**Comment by Ziiiiing** [comment]
Schema in **arcPortals.csv** will be:
- portalName:  `10b-55059`
- URL:  `https://dataportal.kenoshacounty.org/data.json`
- Provider:  `Kenosha County Data Portal`
- titleSource:  `Kenosha County, Wisconsin`
- spatialCoverage:  `Kenosha County, Wisconsin|Wisconsin`
