### ISSUE TITLE
March, 2022 Reharvest

### ISSUE THREAD

**Issue by Ziiiiing** [BTAA-Geospatial-Data-Project/dcat-metadata#46]
- [x] run code
- [x] manually edit  spreadsheet on Google Drive
- [x] upload changes on GitHub Repo
- [x] upload new records to GEOMG 
- [x] retire deleted records 
- [x] update harvest script to make Title field be like AlternativeTitle [Title Source(place name)] {year if exist in alternative title}  
- [x] update harvest script to check duplicates by ID as well

**Comment by karenmajewicz** [comment]
https://docs.google.com/spreadsheets/d/16xJpYhCzVkg073pi3NwC6E1J0cvii9GR3qhmFzdCvf0/edit#gid=1365209124

**Comment by Ziiiiing** [comment]
Lots of duplicated items found between `11a-01` & `11b-39035`
