### ISSUE TITLE
Consolidate Spreadsheet reports

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/dcat-metadata#9]
- Change the reports to just two: NEW and DELETED

- Add a column for code

**Comment by ruetz007** [comment]
Add 1000+ limiter to Socrata

**Comment by karenmajewicz** [comment]
Added this code to the end:

```
#combines all deleted items CSV into one report
csvFile = directory + "allDeletedItems_%s.csv" %  (ActionDate)
with open(csvFile, 'a') as singleFile:
    for csvFile in glob('*_deleted_itemsreport.csv'):
        for line in open(csvFile, 'r'):
            singleFile.write(line)

#combines all new items CSV into one report
csvFile = directory + "allNewItems_%s.csv" %  (ActionDate)
from glob import glob
with open(csvFile, 'a') as singleFile:
    for csvFile in glob('*_new_itemsreport.csv'):
        for line in open(csvFile, 'r'):
            singleFile.write(line)
```

**Comment by karenmajewicz** [comment]
Didn't add a column for code yet.

**Comment by karenmajewicz** [comment]
Didn't include first collection of records

**Comment by smit1975** [comment]
Looks like this issue may be solved for our purposes.  I stumbled on another short script that combines (appends) CSVs and outputs into a new JSON...  another step, but if I understand correctly, we could consolidate the CSVs, output a consolidated JSON, and eventually use our JSON comparison script for comparing with other consolidated JSONs.

https://github.com/ahmedqamesh/json_merge/blob/master/json_merge.py

@karenmajewicz | @mkernik | @ruetz007
